name: 'Fetch organisation contributors'
description: 'Exports organisation contributors to markdown'
author: 'lauravuo'
inputs:
  token:
    required: true
    description: 'GitHub token'
  targetPath:
    required: false
    description: 'Target markdown file path'
    default: './contributors.md'
  commitTarget:
    required: false
    description: 'Save and commit file to repository.'
    default: 'true'
runs:
  using: 'node16'
  main: 'dist/index.js'
